#NAME: Dhanush Nadella
#EMAIL: dnadella787@gmail.com	
#UID: 205150583

default:
	gcc -Wall -Wextra lab1a.c -o lab1a 

clean:
	rm -rf lab1a lab1a-205150583.tar.gz

dist:
	tar -czvf lab1a-205150583.tar.gz lab1a.c README Makefile 