#NAME: Dhanush Nadella,Jeremy Tsujihara
#ID: 205150583,505311626
#EMAIL: dnadella787@gmail.com,jtsujihara@ucla.edu

default:
	ln build.sh lab3b
	chmod +x lab3b
dist:
	tar -czvf lab3b-505311626.tar.gz lab3b.py Makefile README build.sh
clean:
	rm -f lab3b lab3b-505311626.tar.gz
