#NAME: Dhanush Nadella,Jeremy Tsujihara
#ID: 205150583,505311626
#EMAIL: dnadella787@gmail.com,jtsujihara@ucla.edu

default:
	gcc -g -Wall -Wextra -o lab3a lab3a.c -lm
dist:
	tar -czvf lab3a-505311626.tar.gz lab3a.c Makefile README ext2_fs.h
clean:
	rm -f lab3a lab3a-505311626.tar.gz
