#NAME: Dhanush Nadella
#EMAIL: dnadella787@gmail.com
#ID: 205150583

default: 
	tar -czvf lab4a-205150583.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README

dist: default 

clean:
	rm -rf lab4a-205150583.tar.gz
